name: SSH to Oracle VM

on:
  push:
    branches: [ main ]

jobs:
  ssh-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 141.147.108.253
          username: ubuntu
          key: ${{ secrets.OCI_PRIVATE_KEY }}
          script: |
            echo "✅ Connected via GitHub Actions"
            echo 'print("Hello from GitHub!")' > script.py
            python3 script.py > result.txt
            cat result.txt
